"""add resume field

Revision ID: 34103bd256ee
Revises: d671f7e2aae0
Create Date: 2025-04-17 22:44:11.647054

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34103bd256ee"
down_revision: Union[str, None] = "d671f7e2aae0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcription",
        sa.Column("resume", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "transcription",
        "text",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transcription",
        "text",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("transcription", "resume")
    # ### end Alembic commands ###
