"""update_topic_column_type

Revision ID: e4751aebacf7
Revises: 34103bd256ee
Create Date: 2025-04-19 15:16:20.795319

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4751aebacf7"
down_revision: Union[str, None] = "34103bd256ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transcription",
        "topic",
        existing_type=postgresql.ENUM(
            "product",
            "technology",
            "marketing",
            "sales",
            "support",
            "recurrent_meeting",
            name="topic",
        ),
        type_=sa.Enum(
            "product",
            "technology",
            "marketing",
            "sales",
            "support",
            "recurrent_meeting",
            name="topic",
            native_enum=False,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transcription",
        "topic",
        existing_type=sa.Enum(
            "product",
            "technology",
            "marketing",
            "sales",
            "support",
            "recurrent_meeting",
            name="topic",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "product",
            "technology",
            "marketing",
            "sales",
            "support",
            "recurrent_meeting",
            name="topic",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
